# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: bash -c 'cd backend && ruff check --config=pyproject.toml --fix'
        language: system
        types_or: [python, pyi]
        pass_filenames: true
        require_serial: false

      - id: ruff-format
        name: ruff format
        entry: bash -c 'cd backend && ruff format --config=pyproject.toml'
        language: system
        types_or: [python, pyi]
        pass_filenames: true
        require_serial: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--config-file, "backend/pyproject.toml"]
        files: ^backend/
        additional_dependencies:
          - pytest
          - alembic
          - fastapi
          - pydantic
          - pydantic-settings
          - sqlalchemy
          - gunicorn
          - types-PyJWT
          - pyjwt
          - passlib
          - types-passlib
          - bcrypt
          - argon2
          - tenacity

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.2
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        args: [--config, client/eslint.config.js]
        additional_dependencies:
          - eslint
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c 'cd client && npx prettier --write .'
        language: system
        files: \.(ts|tsx|js|jsx|json|css|html)$
        pass_filenames: false
