name: full-stack-fastapi-template-dev

services:
  backend:
    restart: "no"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    # TODO: remove once coverage is done locally
    # volumes:
    #   - ./backend/htmlcov:/app/htmlcov
    # TODO: remove once coverage is done locally
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "${MAILDEV_WEB_PORT?Variable not set}:1080"
      - "${MAILDEV_SMTP_PORT?Variable not set}:1025"