name: full-stack-fastapi-template-main

services:
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.production
    volumes:
      - ./backend/certificates:/app/certificates
    ports:
      - "9000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  